# Generated by Django 5.0.1 on 2024-02-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internet_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fullname', models.CharField(max_length=50)),
                ('connection', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('mob', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('my_files', models.FileField(upload_to='Payment_Screenshot')),
                ('plan', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
