# Generated by Django 5.0.1 on 2024-02-18 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Internet_App', '0003_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signupmaster',
            new_name='signupmaster_admin',
        ),
    ]
