# Generated by Django 5.0.1 on 2024-03-04 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Internet_App', '0007_complain'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='complain',
            new_name='complains',
        ),
    ]
