# Generated by Django 5.0.1 on 2024-03-04 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Internet_App', '0010_complains_delete_complain'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='complains',
            new_name='complain',
        ),
    ]
