# Generated by Django 5.0.1 on 2024-03-04 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Internet_App', '0011_rename_complains_complain'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin_signupmaster',
            new_name='signupmaster',
        ),
    ]
